from tkinter import *
from tkinter import messagebox
window = Tk()
window.title("Поздравление")
window.geometry('500x450')
canvas = Canvas(window, width=500, height=500)
canvas.pack()
lbl2=Label(text="")
lbl2.place(x=75,y=220)
def btn1_click():
    global img
    if var.get()==1:
        img=PhotoImage(file="flowers.png")
    if var.get()==2:
        img=PhotoImage(file="cake.png")
    if var.get()==3:
        img=PhotoImage(file="landscape.png")
    select = list(lbox.curselection())
    lbl2.config(text= ent.get() + ","+lbox.get(select))
    s=canvas.create_image(25,260,anchor=NW,image=img)
var=IntVar()
rbtn1=Radiobutton(text="Квiти",variable=var,value=1)
rbtn2=Radiobutton(text="Торт",variable=var,value=2)
rbtn3=Radiobutton(text="Пейзаж",variable=var,value=3)
rbtn1.place(x=290,y=220)
rbtn2.place(x=290,y=240)
rbtn3.place(x=290,y=260)
btn1 = Button(text="Привiтання", command=btn1_click)
btn1.place(x=25, y=150, width=100, height=50)
btn2 = Button(text="Вихiд", command=window.destroy)
btn2.place(x=150, y=150, width=100, height=50)
ent = Entry()
ent.place(x=150, y=75, width=100, height=30)
lbl = Label(text="Ваше iм`я:")
lbl.place(x=25, y=75, width=60, height=30)
lbl = Label(text="Вiтання:")
lbl.place(x=290, y=50, width=100, height=30)
lbox=Listbox(height=3)
lbox.insert(END,"з 8 березня!")
lbox.insert(1,"з днем народження!")
lbox.insert(2,"з Новим роком!")
lbox.place(x=290,y=100)
lbl = Label(text="Зображення на листiвку:")
lbl.place(x=290, y=180, width=150, height=30)
window.mainloop()
